apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: u1u1bbxcy-python 
  janus-idp.io/tekton: u1u1bbxcy-python
  backstage.io/kubernetes-id: u1u1bbxcy-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: u1u1bbxcy-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml