apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: u1u1bbxcy-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: u1u1bbxcy-python 
  name: u1u1bbxcy-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: u1u1bbxcy-python 
